#spring.data.mongodb.uri = mongodb+srv://mkbhatt_db_user:1000025934@cluster0.fpghnqd.mongodb.net/?appName=Cluster0
#spring.data.mongodb.database = journaldb
#spring.data.mongodb.auto-index-creation=true

#spring.data.mongodb.username = myjournaluser
#spring.data.mongodb.password = mypassword
